name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 현재 프로젝트와 호환되는 Node.js 버전을 사용하세요
      - name: Install Dependencies
        run: npm install # 혹은 yarn install
      - name: Build
        run: npm run build # Vue CLI를 사용하는 경우 일반적인 빌드 스크립트
      # 빌드된 파일을 배포하거나 추가 작업을 수행할 단계를 추가할 수 있습니다.